# Statistics for Data Science [DS401]
## Dictionaries, Lists and Tuples. Part 1
#### By: Javier Orduz

[licenseBDG]: https://img.shields.io/badge/License-CC-orange?style=plastic
[license]: https://creativecommons.org/licenses/by-nc-sa/3.0/deed.en

[mywebsiteBDG]:https://img.shields.io/badge/website-jaorduz.github.io-0abeeb?style=plastic
[mywebsite]: https://jaorduz.github.io/

[mygithubBDG-jaorduz]: https://img.shields.io/badge/jaorduz-repos-blue?logo=github&label=jaorduz&style=plastic
[mygithub-jaorduz]: https://github.com/jaorduz/

[mygithubBDG-jaorduc]: https://img.shields.io/badge/jaorduc-repos-blue?logo=github&label=jaorduc&style=plastic 
[mygithub-jaorduc]: https://github.com/jaorduc/

[myXprofileBDG]: https://img.shields.io/static/v1?label=Follow&message=jaorduc&color=2ea44f&style=plastic&logo=X&logoColor=black
[myXprofile]:https://twitter.com/jaorduc


[![website - jaorduz.github.io][mywebsiteBDG]][mywebsite]
[![Github][mygithubBDG-jaorduz]][mygithub-jaorduz]
[![Github][mygithubBDG-jaorduc]][mygithub-jaorduc]
[![Follow @jaorduc][myXprofileBDG]][myXprofile]
[![CC License][licenseBDG]][license]

## Contents
<div class="alert  alert-block alert-info" style="margin-top: 1px">
    <ol>
        <!-- <li><a href="#unData">Create a function</a></li> -->
         <!-- <ol>
             <li><a href="#reData">Reading</a></li>
         </ol> -->
        <li><a href="#list_tuples">List and Tuples</a></li>
        <li><a href="#exercises">Exercises</a></li>
        <li><a href="#references">References</a></li>
    </ol>
</div>
<br>
<hr>

## 1. Dictionaries, List and Tuples
We call the package

In [1]:
# Import numpy librairy
import numpy as np

We create an set of random mumbers.

In [2]:
#Create a dictionary with 3 key values pairs. For each key value pair it creates a 
# 2x4 matrix of random numbers using the standard normal distribution

data = {i : np.random.randn(2,4) for i in range(3)}

In [3]:
#Print the type of data
type(data)

dict

We print the data with the label from $i= 0$ to $i= 6$

In [4]:
#Print the data
print(data)

{0: array([[ 0.17171071, -0.10169233, -0.54433116, -0.85924197],
       [ 0.47870565, -1.41683461,  0.98564145,  0.06982052]]), 1: array([[-0.91606607,  2.67503204, -0.509699  ,  0.15174552],
       [ 0.30888841, -1.32088189,  1.41107135, -0.13875233]]), 2: array([[-1.57397813,  0.99484695, -0.26080487,  1.43727838],
       [-0.6330638 , -0.31931737,  1.73232432, -0.29097621]])}


In [6]:
# Calculate the average of each column
#Matrix is an integer representing the index of the matrix we want to use
def avg(data, matrix):
    column_averages = np.mean(data[matrix], axis=0)
    print(column_averages)
avg(data,0)
        
    

[ 0.32520818 -0.75926347  0.22065515 -0.39471072]


In [7]:
#Print the value of the first key-value element in the dic
data[0]

array([[ 0.17171071, -0.10169233, -0.54433116, -0.85924197],
       [ 0.47870565, -1.41683461,  0.98564145,  0.06982052]])

In [16]:
# Print the first row of the value of the first key-value element
data[0][0]

array([-0.51529428, -0.39530106,  0.467188  ,  1.45050065])

This is how we extract the 000 element

In [17]:
# Print the first number of the first row of the value of the first key-value element
data[0][0][0]

-0.5152942827164209

## Versions

In [23]:
#Print the python version we are using

from platform import python_version
print("python version: ", python_version())
!pip3 freeze | grep qiskit

python version:  3.11.7


# Exercise

1. Add documentation for the previous code, each line.
1. Calculate the average for the different columns
1. Discuss differences between List and tuples.
4. Create a Jupyter Notebook and solve this NB's questions.
5. Submmit your report in Moodle. Template https://www.overleaf.com/read/xqcnnnrsspcp

In [ ]:
# There is one main difference between a list and a tuple. A list is a mutable type whereas a tuple is immutable. 
# In other word you cannot change the elements of a tuple unlike a list.